# duplicated
root: /eccube3/html/ # root_urlpath
admin_dir: admin/ # admin_route
tpl: /eccube3/html/user_data/packages/default/ # front_urlpath
admin_tpl: /eccube3/html/user_data/packages/admin/ # admin_urlpath
image_path: /eccube3/html/upload/save_image/ # image_save_urlpath

# base valiables
root_dir: /vagrant/eccube3
root_urlpath: /eccube3/html
template_code: default

# routing
admin_route: admin
user_data_route: user_data

# realdir::image
image_save_realdir: /vagrant/eccube3/html/upload/save_image
image_temp_realdir: /vagrant/eccube3/html/upload/temp_image

# realdir::user_data
user_data_realdir: /vagrant/eccube3/html/user_data

# realdir::block
block_default_realdir: /vagrant/eccube3/src/Eccube/Resource/template/default/Block
block_realdir: /vagrant/eccube3/app/template/default/Block
user_block_realdir: /vagrant/eccube3/html/user_data/block

# realdir::template
template_default_realdir: /vagrant/eccube3/src/Eccube/Resource/template/default
template_default_html_realdir: /vagrant/eccube3/html/template/default
template_admin_realdir: /vagrant/eccube3/src/Eccube/Resource/template/admin
template_admin_html_realdir: /vagrant/eccube3/html/template/admin
template_realdir: /vagrant/eccube3/app/template/default
template_html_realdir: /vagrant/eccube3/html/template/default
template_temp_realdir: /vagrant/eccube3/app/cache/eccube/template

# realdir::csv
csv_temp_realdir: /vagrant/eccube3/app/cache/eccube/csv

# urlpath
admin_urlpath: /eccube3/html/template/admin
front_urlpath: /eccube3/html/template/default
image_save_urlpath: /eccube3/html/upload/save_image
image_temp_urlpath: /eccube3/html/upload/temp_image
user_data_urlpath: /eccube3/html/user_data
